export const timeModes = [
  "Paused",
  "SlowMotion",
  "Normal",
  "FastForward",
  "TimeWarp1",
  "TimeWarp2",
  "TimeWarp3",
  "TimeWarp4",
  "TimeWarp5",
  "TimeWarp6",
  "TimeWarp7",
  "TimeWarp8",
  "TimeWarp9",
  "TimeWarp10",
] as const;
