# Simple workflow for deploying static content to GitHub Pages
name: Build and Deploy

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "22"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Generate
        run: pnpm -r generate
      - name: Setup Pages
        id: setupPages
        uses: actions/configure-pages@v5
      - name: Build
        run: pnpm -r build --base=${{ steps.setupPages.outputs.base_path }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./packages/web/dist"
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
